name: Plano de Testes - PI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-latest, ubuntu-latest]
        python-version: ["3.9", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install pytest-cov
      - name: install gemini
        run: |
          pip install -U google.generativeai
      - name: Run pytest
        run: |
          python -m pytest -v
          python -m pytest -W ignore::DeprecationWarning --cov